package de.mertendieckmann.griplbackend.controller

import de.mertendieckmann.griplbackend.application.PreviewGenerator
import de.mertendieckmann.griplbackend.model.dto.EvaluationData
import de.mertendieckmann.griplbackend.model.dto.EvaluationDataMeta
import de.mertendieckmann.griplbackend.model.dto.EvaluationDataWithOptionalId
import de.mertendieckmann.griplbackend.repository.EvaluationDataRepository
import io.github.oshai.kotlinlogging.KotlinLogging
import io.swagger.v3.oas.annotations.Operation
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*
import org.springframework.web.server.ResponseStatusException

@RestController
@CrossOrigin(
    origins = ["\${app.frontend.base-url}"],
    allowCredentials = "true",
    allowedHeaders = ["*"],
    methods = [
        RequestMethod.GET,
        RequestMethod.POST,
        RequestMethod.DELETE,
        RequestMethod.OPTIONS
    ]
)
@RequestMapping("/dataset")
class DatasetController(
    private val evaluationDataRepository: EvaluationDataRepository
) {
    private val log = KotlinLogging.logger { }

    @Operation(
        summary = "Get all Testcases Metadata",
        description = "Returns a list of the metadata of all available processes inside the evaluation dataset."
    )
    @GetMapping("", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun getAllBpmnDatasetMeta(): List<EvaluationDataMeta> {
        val datasets = evaluationDataRepository.getAllEvaluationData()
        if (datasets.isEmpty()) {
            throw ResponseStatusException(HttpStatus.NOT_FOUND, "No datasets found")
        }
        return datasets.map { EvaluationDataMeta(it.id, it.name) }
    }

    @Operation(
        summary = "Insert a new Testcase",
        description = "Inserts a new dataset entry with the provided data. The Id will be automatically generated by the database and returned."
    )
    @PostMapping("")
    fun insertBpmnDataset(@RequestBody evaluationData: EvaluationDataWithOptionalId): ResponseEntity<Int> {
        val idOfCreatedEntry = evaluationDataRepository.insertEvaluationData(evaluationData)
        return if (idOfCreatedEntry != null) {
            ResponseEntity.status(HttpStatus.CREATED).body(idOfCreatedEntry)
        } else {
            ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(-1)
        }
    }

    @Operation(
        summary = "Get Testcase by Id",
        description = "Returns the full testcase entry for a specific Id."
    )
    @GetMapping("/{id}", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun getBpmnDataset(@PathVariable("id") id: Long): EvaluationData {
        val datasetEntry = evaluationDataRepository.getEvaluationDataById(id)
            ?: throw ResponseStatusException(HttpStatus.NOT_FOUND, "No dataset entry found for Id: $id")

        return datasetEntry
    }

    @Operation(
        summary = "Update Testcase by Id",
        description = "Updates an existing dataset entry with the provided data."
    )
    @PostMapping("/{id}")
    fun updateBpmnDataset(@RequestBody evaluationData: EvaluationData): ResponseEntity<String> {
        val existingEntry = evaluationDataRepository.getEvaluationDataById(evaluationData.id)
            ?: return ResponseEntity.status(HttpStatus.NOT_FOUND).body("No dataset entry found for Id: ${evaluationData.id}")

        log.info { "Updating existing dataset entry with Id: ${evaluationData.id}" }

        val affectedRows = evaluationDataRepository.updateEvaluationData(EvaluationData(
            id = existingEntry.id,
            name = evaluationData.name,
            bpmnXml = evaluationData.bpmnXml,
            expectedValues = evaluationData.expectedValues
        ))
        return if (affectedRows > 0) {
            ResponseEntity.ok("Dataset entry updated successfully")
        } else {
            ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Failed to update dataset entry")
        }
    }

    @Operation(
        summary = "Delete Testcase by Id",
        description = "Deletes a specific dataset entry by its Id."
    )
    @DeleteMapping("/{id}")
    fun deleteBpmnDataset(@PathVariable("id") id: Long): ResponseEntity<String> {
        if (evaluationDataRepository.getEvaluationDataById(id) == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("No dataset entry found for Id: $id")
        }

        log.info { "Deleting dataset entry with Id: $id" }

        val affectedRows = evaluationDataRepository.deleteEvaluationData(id)
        return if (affectedRows > 0) {
            ResponseEntity.ok("Dataset entry deleted successfully")
        } else {
            ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Failed to delete dataset entry")
        }
    }

    @Operation(
        summary = "Get SVG Preview of Testcase",
        description = "Generates a SVG preview of the process model for a specific dataset entry by its Id."
    )
    @GetMapping("/{id}/preview", produces = ["image/svg+xml"])
    fun getSvg(
        @PathVariable id: Long,
        @RequestParam correctIds: List<String> = emptyList(),
        @RequestParam falsePositiveIds: List<String> = emptyList(),
        @RequestParam falseNegativeIds: List<String> = emptyList(),
        @RequestParam theme: String = "light"
    ): ResponseEntity<String> {
        val previewGenerator = PreviewGenerator()

        val datasetEntry = evaluationDataRepository.getEvaluationDataById(id)
            ?: return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Kein Datensatz gefunden für Id: $id")
        val bpmnXml = datasetEntry.bpmnXml

        val svg = try {
            previewGenerator.convertXmlToSvg(bpmnXml, correctIds = correctIds, falsePositiveIds = falsePositiveIds, falseNegativeIds = falseNegativeIds, theme = theme)
        } catch (ex: IllegalArgumentException) {
            log.error(ex) { "Ungültiges BPMN XML für Id: $id" }
            return ResponseEntity.badRequest().body("Fehler beim Parsen: ${ex.message}")
        } catch (ex: Exception) {
            log.error(ex) { "Fehler beim Generieren des SVG für Id: $id" }
            return ResponseEntity.status(500).body("Serverfehler: ${ex.message}")
        }

        return ResponseEntity.ok()
            .header("Content-Type", "image/svg+xml")
            .body(svg)
    }
}