import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from 'next-themes'
import "@/style/globals.css";
import "@/style/bpmn-js/bpmn-js.css";
import "@/style/bpmn-js/font-bpmn.css";
import "@/style/bpmn-js/diagram-js.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return <html lang="en" suppressHydrationWarning>
    <head>
        <title>GRIPL</title>
    </head>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen`}>
      <ThemeProvider
        attribute="class"
        value="system"
        defaultTheme="system"
      >
        {children}
      </ThemeProvider>
    </body>
  </html>
}
