name: Build and Push Frontend Docker Image

# This workflow builds and publishes the frontend Docker image to Docker Hub
# To use this in your own fork:
# 1. Set up GitHub repository secrets:
#    - DOCKERHUB_USERNAME: Your Docker Hub username
#    - DOCKERHUB_TOKEN: Your Docker Hub access token
# 2. Update the 'tags' field below with your Docker Hub username
# 3. Update the API_BASE_URL build arg if you want to use a different default

on:
  push:
    branches: [ main ]
    paths:
      - 'gripl/gripl-frontend/**'
      - '.github/workflows/build-frontend-docker.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./gripl/gripl-frontend
          push: true
          # Update 'mertend' with your Docker Hub username
          tags: mertend/gripl-frontend:latest
          platforms: linux/amd64
          build-args: |
            API_BASE_URL=http://localhost:8080
