name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./gripl/gripl-frontend
          push: true
          tags: mertend/gripl-frontend:latest
          build-args: |
            API_BASE_URL=https://gripl.mertendieckmann.de/api

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./gripl/gripl-backend
          push: true
          tags: mertend/gripl-backend:latest
