name: Evaluation

on:
  workflow_dispatch:

jobs:
  evaluete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Start Sprint Boot Application
        run: nohup java -jar target/*.jar > app.log 2>&1 &

      - name: Wait for application to start
        run: |
          sleep 30
          while ! curl -s http://localhost:8080/actuator/health | grep '"status":"UP"'; do
            echo "Waiting for application to start..."
            sleep 5
          done

      - name: Run evaluation
        run: curl --fail http://localhost:8080/gdpr/evaluation -o evaluation-report.md

      - name: Upload evaluation report
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-report
          path: evaluation-report.md
